import { createElement } from 'lwc';
import Snp_No_serchresultPage from 'c/snp_No_serchresultPage';

describe('c-snp-no-serchresult-page', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-snp-no-serchresult-page', {
            is: Snp_No_serchresultPage
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});