import { createElement } from 'lwc';
import TestSNP_customDroipDoWon from 'c/testSNP_customDroipDoWon';

describe('c-test-s-n-p-custom-droip-do-won', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-test-s-n-p-custom-droip-do-won', {
            is: TestSNP_customDroipDoWon
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});